[package]
name = "ssconv"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.24", features = ["derive"] }
color-eyre = "0.6"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
pollster = "0.4"
wgpu = "28.0"

[lints.clippy]
pedantic = "warn"
